### ISSUE TITLE
Multi-line queries sometimes throw errors

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/postgis-preview#24]
![postgis_preview_and_script_js_ _postgis-preview](https://cloud.githubusercontent.com/assets/1833820/15448639/a1602f38-1f35-11e6-8ab3-c3d819057381.png)

If you put your SQL on several lines like in this screenshot it will return an error.  However I have seen the multi-line queries work after deleting the new line and adding again, sometimes... its very odd.

Can anyone repro?

Any ideas on this one @mgd722?

**Comment by mgd722** [comment]
I can reproduce this issue.  I suspect that the newline characters aren't getting coded properly when `editor.getDoc().getValue()` is called.  If you call it manually, you get something that looks right in devtools:
<img width="198" alt="screen shot 2016-05-22 at 08 54 06" src="https://cloud.githubusercontent.com/assets/12187845/15454945/d4a287e0-1ffa-11e6-8e3c-4c133abc03b5.png">

But then when you inspect the API call something gets lost in translation (no space between 'montana_points' and 'where'):
<img width="299" alt="screen shot 2016-05-22 at 08 55 56" src="https://cloud.githubusercontent.com/assets/12187845/15454958/20563bdc-1ffb-11e6-850e-4ec03137ad7a.png">

If I manually add coded spaces to the request all goes well, so this works:
`http://localhost:4000/sql?q=/*%20Type%20your%20SQL%20here%20*/select%20*%20from%20montana_points%20where%20ID%20=%201`

This can probably be solved by encoding the spaces/newlines all as spaces before the API call.  I'll give it a try.

**Comment by chriswhong** [comment]
Cled by #26
